tunnel: doughdistrict-prod
credentials-file: /etc/cloudflared/creds.json

ingress:
  - hostname: doughdistrict.co.za
    service: http://dough-app:80
  - hostname: www.doughdistrict.co.za
    service: http://dough-app:80
  - hostname: db.doughdistrict.co.za
    service: http://localhost:8080
  - service: http_status:404
