name: Deploy DoughDistrict

on:
  push:
    branches: [ main ] # This triggers the "signal"

jobs:
  deploy:
    runs-on: self-hosted # This tells GitHub to talk to your VM
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Deploy
        run: |
          cd ~/homelab/apps/doughdistrict-c2c-ecommerce
          docker compose up -d --build
          docker image prune -f
