- name: Checkout Code
        uses: actions/checkout@v4

      # ADD THIS STEP: It creates the .env file from your GitHub Secrets
      - name: Create .env file
        run: |
          echo "${{ secrets.DOT_ENV }}" > .env

      - name: Docker Deploy
        shell: bash
        run: |
          cd "$GITHUB_WORKSPACE"
          docker compose up -d --build --remove-orphans
          docker system prune -f
